/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-12-16 01:47:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tour;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import tour.Map;

public final class AreaResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>관광정보 안내 서비스</title>\r\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t\t<meta name=\"description\" content=\"\" />\r\n");
      out.write("\t\t<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("\t\t<!--[if lte IE 8]><script src=\"js/html5shiv.js\"></script><![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/skel.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/skel-layers.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/init.js\"></script>\r\n");
      out.write("\t\t<noscript>\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"css/skel.css\" />\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"css/style.css\" />\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"css/style-xlarge.css\" />\r\n");
      out.write("\t\t</noscript>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body class=\"landing\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Header -->\r\n");
      out.write("\t\t\t<header id=\"header\" class=\"alt\">\r\n");
      out.write("\t\t\t\t<h1><strong><a href=\"index.html\">Duksung</a></strong> by youjin</h1>\r\n");
      out.write("\t\t\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Generic</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Elements</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Banner -->\r\n");
      out.write("\t\t\t<section id=\"banner\">\r\n");
      out.write("\t\t\t\t<h2>Duksung</h2>\r\n");
      out.write("\t\t\t\t<p>20131079 컴퓨터학과 박유진</p>\r\n");
      out.write("\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"button special big\">Get Started</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Two -->\r\n");
      out.write("\t\t\t\t<section id=\"two\" class=\"wrapper style2 special\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
 String area = (String)request.getAttribute("area"); 
					//request.setAttribute("area", area);
      out.write("\r\n");
      out.write("\t\t\t\t\t<h1>찾으시는 [");
      out.print(area );
      out.write("] 지역의 관광명소들입니다.</h1>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id=\"map\" style=\"width:100%;height:500px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\" src=\"//apis.daum.net/maps/maps3.js?apikey=d4a5fc60d12d06e0be6a9282fa0bd3aa\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("                                ");
 ArrayList<Map> maps = (ArrayList<Map>)request.getAttribute("maps");
                                ArrayList<Map> titles = (ArrayList<Map>)request.getAttribute("titles"); 
                                int j = 0;
      out.write(" \r\n");
      out.write("                                           \r\n");
      out.write("\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("\t\t\t\t\t\t\t\t\t    mapOption = { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t        center: new daum.maps.LatLng(");
      out.print(maps.get(1).getY() );
      out.write(',');
      out.write(' ');
      out.print(maps.get(0).getX() );
      out.write("), // 지도의 중심좌표\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        level: 3 // 지도의 확대 레벨\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    };\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar map = new daum.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//var markerPosition;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 for(int i = 0; i<maps.size(); i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar markerPosition = new daum.maps.LatLng(");
      out.print(maps.get(i+1).getY() );
      out.write(',');
      out.write(' ');
      out.print(maps.get(i).getX() );
      out.write(");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// 마커를 생성합니다\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar marker = new daum.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmap: map, // 마커를 표시할 지도\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    position: markerPosition,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    title : '");
      out.print(titles.get(j).getTitle() );
      out.write("' \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    //clickable:true // 마커를 클릭했을 때 지도의 클릭 이벤트가 발생하도록 설정합니다\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// 마커가 지도 위에 표시되도록 설정합니다\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmarker.setMap(map);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 System.out.println(i+"번째 : " + maps.get(i+1).getY() + "," + maps.get(i+1).getY() + " ");
										System.out.println(titles.get(j).getTitle());  
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 i++; 
									j++; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// 아래 코드는 지도 위의 마커를 제거하는 코드입니다\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// marker.setMap(null);    \r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("                            \r\n");
      out.write("                        \r\n");
      out.write("                        <br>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"MainPage.jsp\" method=\"GET\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"홈으로\" style=\"background-color:red;\"><br>\r\n");
      out.write("\t\t\t\t\t\t</form> \r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Three -->\r\n");
      out.write("\t\t\t\t<!-- <section id=\"three\" class=\"wrapper style1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</section> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Four -->\r\n");
      out.write("\t\t\t\t<section id=\"four\" class=\"wrapper style3 special\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>웹정보시스템</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>과제</p>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button special big\">Get in touch</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t<footer id=\"footer\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"icons\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-instagram\"></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t<li>&copy; Untitled</li>\r\n");
      out.write("\t\t\t\t\t\t<li>Design: <a href=\"http://templated.co\">TEMPLATED</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>Images: <a href=\"http://unsplash.com\">Unsplash</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
